// LOCALHOST

### Get ALl Processors
GET http://localhost:3000/processor

### Get One Processor 6906a6d26cae19afc9bdcc56
GET http://localhost:3000/processor/6918d62f61996217ee4c34d1

### Create New Processor
POST http://localhost:3000/processor HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "AMD",
    "model": "Ryzen 7 5700X3D",
    "characteristics": {
        "cores": 8,
        "threads": 16,
        "base_clock": "3.0 GHz",
        "max_boost_clock": "4.1 GHz",
        "cache": "96MB L3 Cache",
        "socket": "AM4",
        "integrated_graphics": "No",
        "target_use": "Budget-friendly gaming for older systems"
    },
    "presentation_date": "2024-01-08",
    "initial_price_usd": 249.00
}

### Update Processor by ID
PUT http://localhost:3000/processor/6918d60361996217ee4c34d0 HTTP/1.1
Content-Type: application/json

{
    "model": "Ryzen 7 7800X3D",
    "initial_price_usd": 449
}

### Delete Processor 
DELETE http://localhost:3000/processor/69192de56d609552d46ea257