// LOCALHOST

### Get ALl Processors
GET http://localhost:3000/processor

### Get One Processor 6906a6d26cae19afc9bdcc56
GET http://localhost:3000/processor/6918d62f61996217ee4c34d1

### Create New Processor
POST http://localhost:3000/processor HTTP/1.1
Content-Type: application/json

{
    "manufacturer": "",
    "model": "",
    "characteristics": {
        "cores": 12,
        "threads": 12,
        "max_boost_clock": "3.8 GHz (dual core 4.2 GHz)",
        "architecture": "ARM (System on a Chip)",
        "integrated_graphics": "Yes (Adreno GPU)",
        "target_use": "Windows laptops, exceptional battery life"
    },
    "presentation_date": "2023-10-24",
    "initial_price_usd": null
}

### Update Processor by ID
PUT http://localhost:3000/processor/6918d60361996217ee4c34d0 HTTP/1.1
Content-Type: application/json

{
    "model": "Ryzen 7 7800X3D",
    "initial_price_usd": 449
}

### Delete Processor 
DELETE http://localhost:3000/processor/69192de56d609552d46ea257